spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/linking
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: jws

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

